### ISSUE TITLE
Does it work in Spanish?

### ISSUE THREAD

**Issue by MiClobiMC** [Sba-Stuff/Voice-Clone-Application-Flask-Web-App#1]
I would like to know if this works in a Spanish audio

**Comment by Sba-Stuff** [comment]
I Went this site to download voice sample of Spanish (Neutral):
[Spanish Voice Sample Website](https://worldlyvoices.com/voice-samples/)

As I don't know Spanish, so I used Google Translate to translate the text: "hello world's most popular beautiful princess" I Got:
"hello world's most popular beautiful princess"
![image](https://user-images.githubusercontent.com/36412543/107188259-2ef52600-6a09-11eb-9b93-d8a333412c60.png)


Then I added the voice sample that I downloaded from the above site, and then Spanish translation text;
![image](https://user-images.githubusercontent.com/36412543/107188302-3fa59c00-6a09-11eb-9d65-061ca4d0abb5.png)

Here is the input voice: [Media Fire Input Link](https://www.mediafire.com/file/erysebqolaq1fgt/Voice_Samples_Listen_Here_-_Worldly_Voices.mp3/file)

Here is the output: [Medifire Output Link](https://www.mediafire.com/file/oavds6gwf0lnnhr/Voice_Samples_Listen_Here_-_Worldly_Voices-Output.wav/file)
