### ISSUE TITLE
Exception: Could not find any synthesizer weights under saved_models/default/taco_pretrained

### ISSUE THREAD

**Issue by AIAnytime** [Sba-Stuff/Voice-Clone-Application-Flask-Web-App#2]
Hi, Thanks for the github repo but while running the code, I am getting below error:

`Exception: Could not find any synthesizer weights under saved_models/default/taco_pretrained`

Can you please help me debug this? Thanks in advance!

**Comment by Sba-Stuff** [comment]
You Need to Download and Place Pre-Trained Models In the proper place. Download from here. All 3 of them.

[https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models)
