### ISSUE TITLE
unable to import modules

### ISSUE THREAD

**Issue by Sarekasasikumar** [Sba-Stuff/Voice-Clone-Application-Flask-Web-App#3]
from .encoder.params_model import model_embedding_size as speaker_embedding_size
from .utils.argutils import print_args
from .synthesizer.inference import Synthesizer
from encoder import inference as encoder
from vocoder import inference as vocoder
i cannot seem to import these modules 
and also i have error for no module name helper

**Comment by Sba-Stuff** [comment]
I can not help without seeing your screenshot of the error. Make Sure you have;

1. Python 3.6 and above version (3.6.8 is recommended) x64bit is installed.
2. You have set the python 3.6.8 as environment variable installed.
3. You have extracted all the contents of this code at proper place.
4. You are using correct version of python to open the .py file from the code.

Regards;
**Sba Stuff**
